### ISSUE TITLE
WWC Hackathon 2019 MVP Deliverable 

### ISSUE THREAD

**Issue by alex-blacklocus** [social-housing/affordable-housing-atx#2]
## MVP

Web application in which users enter their zip code, household number (1-5) and yearly income, which returns a list of properties and the estimated maximum monthly rental cost. 

https://docs.google.com/document/d/15jG-CfOHHBOw_hJV-ky8syO-IZ-nbcL6-3M5D115xZA/edit

## Development 

- [x] Back end/API end point work/data #3 
- [x] API/JS layer #4 
- [x] Front end: HTML/CSS form #5 #8 #9 
~- [ ] Movement from HTML/CSS form to React mobile app formulation #6 (Not for MVP)~
~- [ ] Google Maps integration (Not for MVP)~
~- [ ] URL (Not for MVP)~

## Engineering notes

https://dev.socrata.com/foundry/data.austintexas.gov/ngxp-99y3
Signed up for an app token: Signed up. Now I’m able to use their API. 

https://dev.socrata.com
https://github.com/socrata/soda-js
https://github.com/xmunoz/sodapy 

Nice to have: Google Maps integration

## Data notes

Affordable Housing Listing: 
https://data.austintexas.gov/Housing-and-Real-Estate/Affordable-Housing-Listing/ngxp-99y3/data

Information we are getting from the dataset (https://dev.socrata.com/foundry/data.austintexas.gov/ngxp-99y3):
 - Name of location offering affordable housing 
- Zip code
- Adjusted Annual Income 
- Number of persons in household (1-5)

An example calculation using info from COA’s Affordable Housing Listing table and HUD's website: For Lyons Garden location, the maximum qualifying income for 1 person household to household to qualify for the unit is $30,100. If we assume that this is in fact the adjusted income for an individual, that means the potential yearly rental max is 30% of this, or $9,030. This divided by 12 months means the individual can expect to $752.50 per month for an affordable housing unit at this location. 

Data in this table that is potentially useful:
- Zip Code
- Total Affordable Units Available at each location
- Maximum qualifying income for n person household to qualify for the unit (1-5 persons)

Data not available:
- What monthly rental cost to client would be (# 1 question asked by clients). We can calculate this. 

## Product Notes

IDEA: Volunteering as a Financial Coach at Foundation Communities, I encounter clients that struggle to find and evaluate affordable housing options in specific areas of Austin. I'd like to build on the City of Austin Affordable Housing Data project and eventually create a meaningful, accessible mobile application that Foundation Communities clients and their coaches (Or anyone in Austin) can use to potentially identify affordable housing options in Austin and their estimated monthly rental cost. 

LATER (NOT FOR THIS HACKATHON): As a later version of this project, I’d like to expand this data to include housing options for those who do not qualify for affordable housing assistance but are looking for new housing given budgeting requirements, e.g. “I’m looking for a new apartment next month and am willing to pay a maximum of $900 for a one-bedroom in the 78745 area code.” As a greater stretch, perhaps later versions of the mobile application can include web-forms for individuals involved in certain programs and that meet certain criteria to search for and connect with others for support, exchange of ideas and possible roommate interviews. 

The first step of this project (and part of my hackathon idea) is to find, access and aggregate affordable housing data for the city of Austin. After finding and collecting the data, I'd like to analyze the data and see what can be meaningfully extracted and filtered from it. From there, I'd like to build an app that clients can use based on identified filters (rent estimate max per month, zip code, geographic proximity to reliable public transportation).

HUD Guidelines for Affordable Housing: 
https://www.hudexchange.info/programs/home/home-rent-limits/
